### ISSUE TITLE
exec() call to unknown plugin

### ISSUE THREAD

**Issue by matc4** [axemclion/react-native-cordova-plugin#12]
Hello, 

First thank you for your job!

I am having problems to get the Camera plugin working.

I create an empty React App and follow the instructions.

But, when i try to open the Camera this message appears in js error callback:
"Class not found"

And this in the log:
"D/PluginManager(26940): exec() call to unknown plugin: Camera"

Do you have any idea what is missing?

Thanks!

**Comment by axemclion** [comment]
@matiascba I did try it on the camera plugin and was able to get it working. What version of node are yo uusing ? Do you see a camera java class under node_modules/react-native-plugin-adapter/platforms/android ? If not, try deleting node_modules and add it again.

**Comment by matc4** [comment]
Thanks for your reply!.

This is my node version: v4.0.0

I dont have this folder (node_modules/react-native-plugin-adapter/platforms/android)

i have this (node_modules/react-native-cordova-plugin/platforms/android),
but whitout a Camera java class inside

The only Camera java classes are in
(node_modules/cordova-plugin-camera/src/android/CameraLauncher.java)

I try removing the node modules and add it again, but, the same result.

**Comment by matc4** [comment]
I try with the cordova-plugin-device plugin, and everything was OK. 
But the Camera plugin still give me this message in log:
PluginManager(26940): exec() call to unknown plugin: Camera"

**Comment by axemclion** [comment]
Can you share the list of files you have in your project (including the node_modules folder) ? That would help trying to debug the issue. Also, what version of reactnative are you using ?

**Comment by matc4** [comment]
This is the code:
https://github.com/matiascba/react-cordova-camera-test

The react native version is 0.17

**Comment by axemclion** [comment]
@matiascba  I just published 1.0.0 version of this plugin on npm. I also now have an [example app](https://github.com/axemclion/react-native-cordova-plugin/tree/examples) that shows how to use the plugins. It also had a working example of camera

Closing the issue - if you still find this to be an issue, please re-open it.
