### ISSUE TITLE
undefined is not an object (evaluating 'this.nativeInterface.exec')

### ISSUE THREAD

**Issue by gathm5** [axemclion/react-native-cordova-plugin#15]
The "ReactNative.NativeModules.CordovaPluginAdapter" is returned as undefined in node_modules/react-native-cordova-plugin/lib/CordovaPluginAdapter.js

<img width="525" alt="screen shot 2016-02-15 at 1 06 23 pm" src="https://cloud.githubusercontent.com/assets/1642338/13060252/f621df68-d3e4-11e5-9030-4ae00c254fc9.png">

**Comment by axemclion** [comment]
Can you give me a little more information here. What is the plugin you are trying to use ?

**Comment by gathm5** [comment]
I was trying to run the example code from your blog by installing all of the cordova plugins needed for it. The Device, Network Info, Contact, Camera plugin, etc. And all of the plugins were added successfully using the node node_modules/.bin/cordova-plugin add plugin command. Made changes in the gradle settings and mainactivity.java and build was successful as well. On runtime I get this error message.

**Comment by axemclion** [comment]
@gautham1985 You should check out the [example app](https://github.com/axemclion/react-native-cordova-plugin/tree/examples) that shows how to use the plugins. 
Closing the issue - if you still find this to be an issue, please re-open it.
