### ISSUE TITLE
Support cordova-android 5.1.0+?

### ISSUE THREAD

**Issue by kenchengch** [axemclion/react-native-cordova-plugin#16]
Hi Axemclion. This is my first post. I tried to implement of my first React AwesomeProject https://github.com/kenchengch/AwesomeProject. But my App crached when save a new photo(I tried add android.permission.WRITE_EXTERNAL_STORAGE not help). I found that this issuse may be caused by my Android 5.x device (CM12). I found Android support plugin callback results (cordova-android 5.1.0+) may be solved my problem .Will you support cordova-android 5.1.0 framework?

Error:
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=34, result=-1, data=null} to activity {com.awesomeproject/com.awesomeproject.MainActivity}: java.lang.NullPointerException

**Comment by niftylettuce** [comment]
This is related to #14, where I am attempting to get a package that requires v5.0.0+ of Android `platformVersion` working.  I think first, we need to update the dependencies in `package.json` for `cordova-lib` and `cordova-android` via `pnpm install --save cordova-lib@latest cordova-android@latest`, and then maybe see if there are more changes that need to be fixed?

**Comment by kenchengch** [comment]
Hi niftylettuce, 
My ResultInfo seems killed by android system lifecycle.
I think the axemclion/react-native-cordova-plugin should support cordova-android 5.1.0 new features as follows,

http://cordova.apache.org/docs/en/dev/guide/platforms/android/plugin.html

/**
- Called when the Activity is being destroyed (e.g. if a plugin calls out to an
- external Activity and the OS kills the CordovaActivity in the background).
- The plugin should save its state in this method only if it is awaiting the
- result of an external Activity and needs to preserve some information so as
- to handle that result; onRestoreStateForActivityResult() will only be called
- if the plugin is the recipient of an Activity result
  *
- @return  Bundle containing the state of the plugin or null if state does not
-          need to be saved
  */
  public Bundle onSaveInstanceState() {}

**Comment by axemclion** [comment]
@kenchengch @niftylettuce I have started working on this, here is the update https://github.com/axemclion/react-native-cordova-plugin/commit/76496c646881f0c875eb2129d8e463b6937cc9a8

I am not going to test it with a couple of plugins, and should publish a new version

**Comment by axemclion** [comment]
@kenchengch @niftylettuce I just published 1.0.0 version of this plugin on npm. I also now have an [example app](https://github.com/axemclion/react-native-cordova-plugin/tree/examples) that shows how to use the plugins. 

Closing the issue - if you still find this to be an issue, please re-open it.
