### ISSUE TITLE
no command "react-native-cordova-plugin" in windows.

### ISSUE THREAD

**Issue by liiklin** [axemclion/react-native-cordova-plugin#22]
Hi,my os is windows,it seems no react-native-cordova-plugin in the path。
Hope to get your help。

**Comment by axemclion** [comment]
@liiklin Can you try running `node node_modules/react-native-cordova-plugin/cli/cli.js add cordova-plugin-camera` instead ?

**Comment by liiklin** [comment]
@axemclion is works.
