### ISSUE TITLE
Requiring unknown module "RCTDeviceEventEmitter"

### ISSUE THREAD

**Issue by MichelKansou** [axemclion/react-native-cordova-plugin#24]
Hi,
Im using react native v0.24.1, I have problem with cordova-plugin Im getting this error

`Requiring unknown module "RCTDeviceEventEmitter".If you are sure the module is there, try restarting the packager or running "npm install".`

and I found that in CordovaPluginAdapter.js 

`var RCTDeviceEventEmitter = require('RCTDeviceEventEmitter');` 

if I replace it with `import { DeviceEventEmitter } from 'react-native';` it work but I get another one `document is not defined`
Im stuck here and I really want to know is it coming from react native version or from my code.
Here's my current code for now : 

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 */

import React, {
  AppRegistry,
  Component,
  StyleSheet,
  Text,
  View
} from 'react-native';

import Cordova from 'react-native-cordova-plugin';

class NFCDemo extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.android.js
        </Text>
        <Text style={styles.instructions}>
          Shake or press menu button for dev menu
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('NFCDemo', () => NFCDemo);

```

Any advice and suggestions will be greatly appreciated.

**Comment by axemclion** [comment]
@MichelKansou I tested this on react-native 0.22, looks like these are changes in 0.24. I will look into them.

**Comment by axemclion** [comment]
@MichelKansou What is the plugin that you are using ? I am working on fixing the `DeviceEmitter` issue, but looks like the document part could be due to the plugin. If you tell me the name of the plugin, I could take a look.

**Comment by axemclion** [comment]
@MichelKansou I released a 1.0.1 version of the package, that fixes the deviceEmitter issue.

**Comment by MichelKansou** [comment]
@axemclion Sorry for the late answer, thank you I will test it and I'm using cordova-plugin-device if everything work fine I want to use phonegap-nfc tell me if you know a better plugin for NFC would be nice.

**Comment by MichelKansou** [comment]
@axemclion After testing with cordova-plugin-device it work but when I install phonegap-nfc it give an error saying `document is not defined` in cordova.js

**Comment by MichelKansou** [comment]
it's coming from `react-native-cordova-plugin/platforms/android/assets/www/cordova.js`

**Comment by axemclion** [comment]
@MichelKansou That `react-native-cordova-plugin/platforms/android/assets/www/cordova.js` is actually generated from  the files in the plugin itself. Looks like the offending statement is due to the use of [document.addeventListener](https://github.com/chariotsolutions/phonegap-nfc/blob/master/www/phonegap-nfc.js#L30)
In ReactNative, you don't really have a `document` object. One way to fix it would be be clone the repo, and replace all `document.addEventListeners` with an eventing mechanism that lives on a global object. The add event listener part is just to send back the results, which is already sent back in the `win/fail` callbacks.

**Comment by MichelKansou** [comment]
@axemclion Thank you, I didn't find a way to make it work with react-native, I will try to make a native module for NFC
