### ISSUE TITLE
Cordova View ?

### ISSUE THREAD

**Issue by pagrawl3** [axemclion/react-native-cordova-plugin#3]
Hello, I am kinda new to this, so pardon if this is a redundant question. Is there a way to embed a cordova view as a subview inside react-native ? Let's say a video player or the webview itself.

Any help would be appreciated !

**Comment by axemclion** [comment]
Give that a ReactNative app is still a native app, you should be able to use Cordova Embedded Views to accomplish this.

**Comment by ghost** [comment]
By Using Cordova Embedded Views do you mean writing a bridge for the embeddable webviews specific to the platform or there something simpler I'm missing?

**Comment by axemclion** [comment]
@karannakai Technically, Cordova Embedded WebView should already have all the infrastructure for the bridge, as I saw here - https://github.com/infil00p/CordovaComponentCase

By using that, you will already have access to the bridge, right ?
