### ISSUE TITLE
support for npm 3 

### ISSUE THREAD

**Issue by maxim-c** [axemclion/react-native-cordova-plugin#5]
not wokring with npm 3.

**Comment by axemclion** [comment]
Is this extension itself an issue, or is the issue with individual plugins ? Can you help me understand the issue ?

**Comment by maxim-c** [comment]
this is with extension itself. There a   70+ errors (some of them “java: package org.apache.cordova does not exist”) . I suppose it just cant find dependencies, because looking in ./react-native-cordova-plugin/node_modules/, but actually in npm 3 they installed in  project's node_modules

**Comment by axemclion** [comment]
Just ran it with npm3, and I see the errors. Cordova is working on updating to using Node 5, and as soon as that happens, I will update this plugin to start using the new model.
