### ISSUE TITLE
Requiring unknown module "rncp". If you are sure the  module  is there , try restarting  the packager.

### ISSUE THREAD

**Issue by Sharathnasa** [axemclion/react-native-cordova-plugin#6]
Hello Parashuram,

Thanks a lot for letting me know on how to use the cordova plugin in react-native. You saved my day. I have followed your blog to add the plugin and just to test whether i have properly done the setup, i have used your sample Index.android.js file. But when i run the app, its showing the above error(Which i have mentioned in the title).

Could you please help me in this..

Regards,
Sharath

**Comment by maxim-c** [comment]
@Sharathnasa 
change "rncp" to "react-native-cordova-plugin" in index.android.js file.

**Comment by axemclion** [comment]
Thanks @Deadlysmile - closing this as this is not an issue any more.

**Comment by Sharathnasa** [comment]
I have tired even that before raising this as the issue. still displayed the same. Should i need to add package and module(Like how we add while writing the plugin for react-native to javascript).

Any help will be appreciated. Because this didn't worked for me, i'm writing the plugin in React-Native to fetch the list of installed application with package name along with the image(which gets stored in the sdcard) which i had written for cordova. If this is the case for my requirement(the app which i'm building) requires a lot of plugins to be re-written in react-native.

Please help me in this regard. If you need any further details, i'm ready to provide.

Regards,
Sharathnasa

**Comment by axemclion** [comment]
Can you add the code from indexo.android.js ?

**Comment by Sharathnasa** [comment]
Thanks for replying axemclion. Sure i will paste below. Also i will attaching my project, just for reference(This project doesn't contain any complicated things. Only i have follwed your blog and added device info plugin.) link for the project - https://drive.google.com/file/d/0B3JBaN1pWSAPdk0zeXBQX1lxSDQ/view?usp=sharing

Also below error was logging inside logcat.

error:
1. 'Error: Requiring unknown module "react-native-cordova-plugin". If you are sure the module is there, try restarting the packager.\n stack: \n  requireImpl  index.android.bun…:48\n  require      index.android.bun…:26\n  <unknown>    index.android.bun…:903\n  requireImpl  index.android.bun…:64\n  requireImpl  index.android.bun…:34\n  require      index.android.bun…:26\n  <unknown>    index.android.bun…:52671\n URL: http://10.0.3.2:8081/index.android.bundle?platform=android&dev=true\n line: 48\n message: Requiring unknown module "react-native-cordova-plugin". If you are sure the module is there, try restarting the packager.'

2.'Error: Invariant Violation: Application AwesomeApp has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.\n stack: \n  runApplication  index.android.bun…:45866\n  __callFunction    index.android.bun…:2517\n  <unknown> index.android.bun…:2443\n  guard index.android.bun…:2402\n  callFunctionReturnFlushedQueue  index.android.bun…:2442\n URL: http://10.0.3.2:8081/index.android.bundle?platform=android&dev=true\n line: 3019\n message: Invariant Violation: Application AwesomeApp has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.'

Please find the android.index.js contents as below:

/**
- Sample React Native App
- https://github.com/facebook/react-native
  */
  'use strict';

var React = require('react-native');
var cordova = require('react-native-cordova-plugin');
cordova.device.getInfo(console.log.bin(console.log), console.log.bind(console));
var {
  AppRegistry,
  StyleSheet,
  Text,
  View,
} = React;

var AwesomeApp = React.createClass({
  render: function() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.android.js
        </Text>
        <Text style={styles.instructions}>
          Shake or press menu button for dev menu
        </Text>
      </View>
    );
  }
});

var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('AwesomeApp', () => AwesomeApp);

Please let me know if require any further details.

Regards,
Sharathnasa

**Comment by niftylettuce** [comment]
@axemclion The example gist you link from the Readme.md file still has `rncp` in it per https://gist.github.com/axemclion/b30bdfe991e509851705#file-index-android-js-L14

**Comment by axemclion** [comment]
@niftylettuce I think that is a bug - probably should remove that.
