### ISSUE TITLE
require('react-native-cordova-plugin') returns undefined

### ISSUE THREAD

**Issue by skyride99** [axemclion/react-native-cordova-plugin#9]
Went through the steps

Project is at https://github.com/skyride99/z3

Thanks for the Cordova this is a great idea!

using the cordova-plugin-eddystone

**Comment by skyride99** [comment]
I am using node 4.0.0
 and npm 2.14.2./ and npm 3.3.6 
this is on El Captian

**Comment by roysG** [comment]
is this solved?

**Comment by axemclion** [comment]
@roysG I am looking into this right now.

**Comment by roysG** [comment]
+1

**Comment by roysG** [comment]
When ios also be valid for using ?

**Comment by axemclion** [comment]
@roysG I am not an iOS expert, so would appretiate any help in that aspect.

**Comment by axemclion** [comment]
@skyride99 I looked into this and I was not able to repro this. Note that I had the `react-native-cordova-plugin` installed and as mentioned in this plugin's package.json, I am able to load the plugin-adapter.

I would need some more help from you to debug this issue. Can you confirm the following
- `node_modules/react-native-cordova-plugin` folder exists
- under the folder above, you are able to see a `lib/index.js`, and package.json points to that.

**Comment by axemclion** [comment]
Ping @skyride99 Were you able to resolve this ?

**Comment by skyride99** [comment]
Yes with v16 of react native it works well. v14 and 14.3 not working.

**Comment by axemclion** [comment]
Awesome thanks - closing the issue.
